coverage:
  range: 80..100
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

codecov:
  require_ci_to_pass: false

ignore:
  - "tests/**/*"
