# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 10:05
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name=b'Achieved'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='targeted',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name=b'Targeted'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name=b'Achieved'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='targeted',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name=b'Targeted'),
        ),
    ]
