# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20170105_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregationlabel',
            name='customsort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
