# Generated by Django 2.2.10 on 2020-02-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20200215_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
