# Generated by Django 2.2.1 on 2019-05-28 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20190527_2331'),
        ('indicators', '0002_auto_20190513_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicobjective',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='indicators.StrategicObjective'),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
