# Generated by Django 2.2.10 on 2020-02-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20200215_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregationtype',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disaggregation_label', to='indicators.Indicator'),
        ),
    ]
