# Generated by Django 2.2.4 on 2019-09-17 05:08

from django.db import migrations


def populate_data_collection_frequency_defaults(apps, schema_editor):
    DataCollectionFrequency = apps.get_model('indicators', 'DataCollectionFrequency')
    frequencies = ('Monthly', 'Quarterly', 'Biannual', 'Annual', 'Life of Project')

    for frequency in frequencies:
        DataCollectionFrequency.objects.create(frequency=frequency)


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_objective_parent'),
    ]

    operations = [
        migrations.RunPython(populate_data_collection_frequency_defaults),
    ]
