# Generated by Django 2.2.4 on 2019-09-17 14:01

from django.db import migrations


def populate_reporting_frequency_defaults(apps, schema_editor):
    ReportingFrequency = apps.get_model('indicators', 'ReportingFrequency')
    frequencies = (
        'Monthly',
        'Quarterly',
        'Biannual',
        'Annual',
        'Life of Project'
    )

    for frequency in frequencies:
        ReportingFrequency.objects.create(frequency=frequency)


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20190916_2208'),
    ]

    operations = [
        migrations.RunPython(populate_reporting_frequency_defaults),
    ]
