# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-10 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20170509_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collecteddata',
            name='targeted',
        ),
        migrations.RemoveField(
            model_name='historicalcollecteddata',
            name='targeted',
        ),
    ]
