# Generated by Django 2.2.10 on 2020-02-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_stakeholdertype_organization'),
        ('indicators', '0006_datacollectionfrequency_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Organization'),
        ),
    ]
