# Generated by Django 2.2.10 on 2020-02-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_datacollectionfrequency_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatortype',
            name='description',
            field=models.TextField(blank=True, max_length=765, null=True),
        ),
    ]
