# Generated by Django 2.2.7 on 2019-12-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_auto_20191007_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictarget',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
