# Generated by Django 2.2.10 on 2020-02-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_auto_20200227_2054'),
        ('indicators', '0008_auto_20200226_0808'),
    ]

    operations = [
    ]
