# Generated by Django 2.2.5 on 2019-12-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20191112_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregationlabel',
            name='disaggregation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaggregation_label', to='indicators.DisaggregationType'),
        ),
    ]
