# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20170516_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicator',
            name='information_use',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Information Use'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='information_use',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Information Use'),
        ),
    ]
