# Generated by Django 2.2.7 on 2019-12-29 04:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_auto_20191202_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='achieved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Achieved'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='indicator',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.Indicator'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='targeted',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True, verbose_name='Targeted'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='achieved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Achieved'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='targeted',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True, verbose_name='Targeted'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='target_frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Life of Program (LoP) only'), (2, 'Midline and endline'), (3, 'Annual'), (4, 'Semi-annual'), (5, 'Tri-annual'), (6, 'Quarterly'), (7, 'Monthly'), (8, 'Event')], help_text=' ', null=True, verbose_name='Target frequency'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Life of Program (LoP) only'), (2, 'Midline and endline'), (3, 'Annual'), (4, 'Semi-annual'), (5, 'Tri-annual'), (6, 'Quarterly'), (7, 'Monthly'), (8, 'Event')], help_text=' ', null=True, verbose_name='Target frequency'),
        ),
    ]
