# Generated by Django 2.2.10 on 2020-03-11 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_organization_location_description'),
        ('indicators', '0009_merge_20200228_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
