# Generated by Django 2.2.10 on 2020-03-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_auto_20200311_1152'),
        ('indicators', '0010_auto_20200310_1010'),
    ]

    operations = [
    ]
