# Generated by Django 2.2.7 on 2020-01-06 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_auto_20191228_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytable',
            options={'verbose_name': 'Activity Table', 'verbose_name_plural': 'Activity Tables'},
        ),
        migrations.AlterModelOptions(
            name='collecteddata',
            options={'ordering': ('agreement', 'indicator', 'date_collected', 'create_date'), 'verbose_name_plural': 'Collected Data'},
        ),
        migrations.AlterModelOptions(
            name='datacollectionfrequency',
            options={'ordering': ('frequency',), 'verbose_name': 'Data Collection Frequency', 'verbose_name_plural': 'Data Collection Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='disaggregationlabel',
            options={'ordering': ('customsort',), 'verbose_name': 'Disaggregation Label', 'verbose_name_plural': 'Disaggregation Labels'},
        ),
        migrations.AlterModelOptions(
            name='disaggregationtype',
            options={'ordering': ('country', 'disaggregation_type'), 'verbose_name': 'Disaggregation Type', 'verbose_name_plural': 'Disaggregation Types'},
        ),
        migrations.AlterModelOptions(
            name='externalservice',
            options={'verbose_name': 'External Service', 'verbose_name_plural': 'External Services'},
        ),
        migrations.AlterModelOptions(
            name='externalservicerecord',
            options={'verbose_name': 'External Service Record', 'verbose_name_plural': 'External Service Records'},
        ),
        migrations.AlterModelOptions(
            name='indicatortype',
            options={'ordering': ('indicator_type',), 'verbose_name_plural': 'Indicator Types'},
        ),
        migrations.AlterModelOptions(
            name='periodictarget',
            options={'ordering': ('customsort', '-create_date'), 'verbose_name': 'Periodic Target', 'verbose_name_plural': 'Periodic Targets'},
        ),
        migrations.AlterModelOptions(
            name='reportingfrequency',
            options={'ordering': ('frequency',), 'verbose_name': 'Reporting Frequency', 'verbose_name_plural': 'Reporting Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='strategicobjective',
            options={'ordering': ('country', 'name'), 'verbose_name_plural': 'Strategic Objectives'},
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.DataCollectionFrequency', verbose_name='Data Collection Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='justification',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Justification for Indicator'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='means_of_verification',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Means of Verification'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.ReportingFrequency', verbose_name='Reporting Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='responsible_person',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Responsible Person or Team'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.DataCollectionFrequency', verbose_name='Data Collection Frequency'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='justification',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Justification for Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='means_of_verification',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Means of Verification'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ReportingFrequency', verbose_name='Reporting Frequency'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='responsible_person',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Responsible Person or Team'),
        ),
    ]
