# Generated by Django 2.2.7 on 2020-01-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_auto_20200109_2051'),
        ('indicators', '0011_auto_20200105_2135'),
    ]

    operations = [
    ]
