# Generated by Django 2.2.7 on 2020-02-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0012_merge_20200109_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicator',
            name='baseline',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.DataCollectionFrequency', verbose_name='Data collection frequency'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_collection_method',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Data collection method'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_issues',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Data issues'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_points',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Data points'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='indicator_changes',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Changes to indicator'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='information_use',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Information use'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='justification',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Justification for indicator'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='lop_target',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Overall target'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='means_of_verification',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Means of verification'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='method_of_analysis',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Method of analysis'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='quality_assurance',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Quality assurance measures'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.ReportingFrequency', verbose_name='Reporting frequency'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='responsible_person',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Responsible person or team'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='source',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Data source'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='target_frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Life of Program only'), (2, 'Midline and endline'), (3, 'Annual'), (4, 'Semi-annual'), (5, 'Tri-annual'), (6, 'Quarterly'), (7, 'Monthly'), (8, 'Event')], help_text=' ', null=True, verbose_name='Target frequency'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text=' ', max_length=135, null=True, verbose_name='Unit of measure'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='baseline',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.DataCollectionFrequency', verbose_name='Data collection frequency'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_method',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Data collection method'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_issues',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Data issues'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_points',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Data points'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_changes',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Changes to indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='information_use',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Information use'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='justification',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Justification for indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lop_target',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Overall target'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='means_of_verification',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Means of verification'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='method_of_analysis',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Method of analysis'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='objectives',
            field=models.ManyToManyField(blank=True, help_text=' ', related_name='obj_indicator', to='indicators.Objective', verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='quality_assurance',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Quality assurance measures'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ReportingFrequency', verbose_name='Reporting frequency'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='responsible_person',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Responsible person or team'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Data source'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='strategic_objectives',
            field=models.ManyToManyField(blank=True, help_text=' ', related_name='strat_indicator', to='indicators.StrategicObjective', verbose_name='Strategic objective'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Life of Program only'), (2, 'Midline and endline'), (3, 'Annual'), (4, 'Semi-annual'), (5, 'Tri-annual'), (6, 'Quarterly'), (7, 'Monthly'), (8, 'Event')], help_text=' ', null=True, verbose_name='Target frequency'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text=' ', max_length=135, null=True, verbose_name='Unit of measure'),
        ),
    ]
