# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_auto_20180118_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=2, help_text=b' ', max_digits=20, verbose_name=b'Achieved'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_agreement2', to='workflow.ProjectAgreement', verbose_name=b'Project Initiation'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_data', to='workflow.TolaUser', verbose_name=b'Originated By'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='comment',
            field=models.TextField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name=b'Comment/Explanation'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='complete',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_complete2', to='workflow.ProjectComplete'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='date_collected',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='description',
            field=models.TextField(blank=True, help_text=b' ', null=True, verbose_name=b'Remarks/comments'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, help_text=b' ', to='indicators.DisaggregationValue'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='evidence',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Documentation', verbose_name=b'Evidence Document or Link'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='indicator',
            field=models.ForeignKey(help_text=b' ', on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='periodic_target',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.PeriodicTarget'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='program',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_program', to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='site',
            field=models.ManyToManyField(blank=True, help_text=b' ', to='workflow.SiteProfile'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='tola_table',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.TolaTable'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, help_text=b' ', verbose_name=b'Would you like to update the achieved total with the row count from TolaTables?'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=2, help_text=b' ', max_digits=20, verbose_name=b'Achieved'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='comment',
            field=models.TextField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name=b'Comment/Explanation'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='date_collected',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='description',
            field=models.TextField(blank=True, help_text=b' ', null=True, verbose_name=b'Remarks/comments'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, help_text=b' ', verbose_name=b'Would you like to update the achieved total with the row count from TolaTables?'),
        ),
    ]
