# Generated by Django 2.2.7 on 2020-02-11 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_auto_20200204_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregationtype',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disaggregation_label', to='indicators.Indicator'),
        ),
    ]
