# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_auto_20180119_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodictarget',
            options={'ordering': ('customsort', '-create_date')},
        ),
    ]
