# Generated by Django 2.2.10 on 2020-02-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_disaggregationtype_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
