# Generated by Django 2.2 on 2019-05-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0015_auto_20180202_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=2, help_text=' ', max_digits=20, verbose_name='Achieved'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_agreement2', to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_data', to='workflow.TolaUser', verbose_name='Originated By'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='comment',
            field=models.TextField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Comment/Explanation'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='complete',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_complete2', to='workflow.ProjectComplete'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='date_collected',
            field=models.DateTimeField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='description',
            field=models.TextField(blank=True, help_text=' ', null=True, verbose_name='Remarks/comments'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, help_text=' ', to='indicators.DisaggregationValue'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='evidence',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Documentation', verbose_name='Evidence Document or Link'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='indicator',
            field=models.ForeignKey(help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.Indicator'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='periodic_target',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.PeriodicTarget'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='program',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='i_program', to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='site',
            field=models.ManyToManyField(blank=True, help_text=' ', to='workflow.SiteProfile'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='tola_table',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.TolaTable'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, help_text=' ', verbose_name='Would you like to update the achieved total with the row count from TolaTables?'),
        ),
        migrations.AlterField(
            model_name='datacollectionfrequency',
            name='numdays',
            field=models.PositiveIntegerField(default=0, verbose_name='Frequency in number of days'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='standard',
            field=models.BooleanField(default=False, verbose_name='Standard (TolaData Admins Only)'),
        ),
        migrations.AlterField(
            model_name='externalservicerecord',
            name='external_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ExternalService'),
        ),
        migrations.AlterField(
            model_name='externalservicerecord',
            name='record_id',
            field=models.CharField(blank=True, max_length=765, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=2, help_text=' ', max_digits=20, verbose_name='Achieved'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='agreement',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser', verbose_name='Originated By'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='comment',
            field=models.TextField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Comment/Explanation'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='complete',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectComplete'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='date_collected',
            field=models.DateTimeField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='description',
            field=models.TextField(blank=True, help_text=' ', null=True, verbose_name='Remarks/comments'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='evidence',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Documentation', verbose_name='Evidence Document or Link'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='indicator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.Indicator'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='periodic_target',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.PeriodicTarget'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='tola_table',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.TolaTable'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, help_text=' ', verbose_name='Would you like to update the achieved total with the row count from TolaTables?'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='approval_submitted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='baseline',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Baseline*'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='baseline_na',
            field=models.BooleanField(default=False, help_text=' ', verbose_name='Not applicable'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='comments',
            field=models.TextField(blank=True, help_text=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.DataCollectionFrequency', verbose_name='Frequency of Data Collection'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_collection_method',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Data Collection Method'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_issues',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Data Issues'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_points',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Data Points'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='definition',
            field=models.TextField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='external_service_record',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.ExternalServiceRecord', verbose_name='External Service ID'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='indicator_changes',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Changes to Indicator'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='information_use',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Information Use'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='justification',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Rationale or Justification for Indicator'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='key_performance_indicator',
            field=models.BooleanField(default=False, help_text=' ', verbose_name='Key Performance Indicator for this program?'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='lop_target',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Life of Program (LoP) target*'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='means_of_verification',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Means of Verification / Data Source'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='method_of_analysis',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Method of Analysis'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='name',
            field=models.CharField(help_text=' ', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='number',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='quality_assurance',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Quality Assurance Measures'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='rationale_for_target',
            field=models.TextField(blank=True, help_text=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.ReportingFrequency', verbose_name='Frequency of Reporting'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='responsible_person',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Responsible Person(s) and Team'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='sector',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Sector'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='source',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='target_frequency',
            field=models.IntegerField(choices=[(1, 'Life of Program (LoP) only'), (2, 'Midline and endline'), (3, 'Annual'), (4, 'Semi-annual'), (5, 'Tri-annual'), (6, 'Quarterly'), (7, 'Monthly'), (8, 'Event')], help_text=' ', null=True, verbose_name='Target frequency'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='target_frequency_custom',
            field=models.CharField(blank=True, help_text=' ', max_length=100, null=True, verbose_name='First event name*'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='target_frequency_num_periods',
            field=models.IntegerField(blank=True, help_text=' ', null=True, verbose_name='Number of target periods*'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='target_frequency_start',
            field=models.DateField(blank=True, help_text=' ', null=True, verbose_name='First target period begins*'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text=' ', max_length=135, null=True, verbose_name='Unit of measure*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='approval_submitted_by',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_submitted_by', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_indicator', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='baseline',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Baseline*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='baseline_na',
            field=models.BooleanField(default=False, help_text=' ', verbose_name='Not applicable'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='comments',
            field=models.TextField(blank=True, help_text=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.DataCollectionFrequency', verbose_name='Frequency of Data Collection'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_method',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Data Collection Method'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_issues',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Data Issues'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_points',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Data Points'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='definition',
            field=models.TextField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='disaggregation',
            field=models.ManyToManyField(blank=True, help_text=' ', to='indicators.DisaggregationType'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='external_service_record',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ExternalServiceRecord', verbose_name='External Service ID'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_changes',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Changes to Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.ManyToManyField(blank=True, help_text=' ', to='indicators.IndicatorType'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='information_use',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Information Use'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='justification',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Rationale or Justification for Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='key_performance_indicator',
            field=models.BooleanField(default=False, help_text=' ', verbose_name='Key Performance Indicator for this program?'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='level',
            field=models.ManyToManyField(blank=True, help_text=' ', to='indicators.Level'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lop_target',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Life of Program (LoP) target*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='means_of_verification',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Means of Verification / Data Source'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='method_of_analysis',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Method of Analysis'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(help_text=' ', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='number',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='objectives',
            field=models.ManyToManyField(blank=True, help_text=' ', related_name='obj_indicator', to='indicators.Objective', verbose_name='Program Objective'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='program',
            field=models.ManyToManyField(help_text=' ', to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='quality_assurance',
            field=models.TextField(blank=True, help_text=' ', max_length=500, null=True, verbose_name='Quality Assurance Measures'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='rationale_for_target',
            field=models.TextField(blank=True, help_text=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ReportingFrequency', verbose_name='Frequency of Reporting'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='responsible_person',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True, verbose_name='Responsible Person(s) and Team'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(blank=True, help_text=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Sector'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, help_text=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='strategic_objectives',
            field=models.ManyToManyField(blank=True, help_text=' ', related_name='strat_indicator', to='indicators.StrategicObjective', verbose_name='Country Strategic Objective'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency',
            field=models.IntegerField(choices=[(1, 'Life of Program (LoP) only'), (2, 'Midline and endline'), (3, 'Annual'), (4, 'Semi-annual'), (5, 'Tri-annual'), (6, 'Quarterly'), (7, 'Monthly'), (8, 'Event')], help_text=' ', null=True, verbose_name='Target frequency'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency_custom',
            field=models.CharField(blank=True, help_text=' ', max_length=100, null=True, verbose_name='First event name*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency_num_periods',
            field=models.IntegerField(blank=True, help_text=' ', null=True, verbose_name='Number of target periods*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency_start',
            field=models.DateField(blank=True, help_text=' ', null=True, verbose_name='First target period begins*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text=' ', max_length=135, null=True, verbose_name='Unit of measure*'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ReportingFrequency'),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
    ]
