# Generated by Django 2.2 on 2019-05-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectAgreement'),
        ),
        migrations.AlterField(
            model_name='report',
            name='collected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.CollectedData'),
        ),
        migrations.AlterField(
            model_name='report',
            name='complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectComplete'),
        ),
        migrations.AlterField(
            model_name='report',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Status Description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.Indicator'),
        ),
        migrations.AlterField(
            model_name='report',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Program'),
        ),
    ]
