# Generated by Django 2.2 on 2019-05-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('workflow', '0001_initial'),
        ('indicators', '0002_auto_20190519_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectAgreement'),
        ),
        migrations.AddField(
            model_name='report',
            name='collected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.CollectedData'),
        ),
        migrations.AddField(
            model_name='report',
            name='complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectComplete'),
        ),
        migrations.AddField(
            model_name='report',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
        migrations.AddField(
            model_name='report',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.Indicator'),
        ),
        migrations.AddField(
            model_name='report',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Program'),
        ),
    ]
