# Generated by Django 2.2.10 on 2020-04-28 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_merge_20200426_1805'),
        ('formlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='workflow.Contact'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='workflow.Contact'),
        ),
        migrations.AddField(
            model_name='training',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='workflow.Contact'),
        ),
        migrations.RemoveField(
            model_name='construction',
            name='cases',
        ),
        migrations.AddField(
            model_name='construction',
            name='cases',
            field=models.ManyToManyField(blank=True, to='formlibrary.Case'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='implementer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Stakeholder'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Program'),
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='cases',
        ),
        migrations.AddField(
            model_name='distribution',
            name='cases',
            field=models.ManyToManyField(blank=True, to='formlibrary.Case'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='implementer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Stakeholder'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Program'),
        ),
        migrations.RemoveField(
            model_name='training',
            name='cases',
        ),
        migrations.AddField(
            model_name='training',
            name='cases',
            field=models.ManyToManyField(blank=True, to='formlibrary.Case'),
        ),
        migrations.AlterField(
            model_name='training',
            name='implementer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Stakeholder'),
        ),
        migrations.AlterField(
            model_name='training',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='workflow.Contact'),
        ),
    ]
