# Generated by Django 2.2 on 2019-05-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='site',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.SiteProfile'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='initiation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='office_code',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Office'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='program',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='province',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Province'),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='program',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='project_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
    ]
