# Generated by Django 2.2.10 on 2020-04-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0002_auto_20200427_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_of', to='workflow.Contact'),
        ),
    ]
