# Generated by Django 2.2.10 on 2020-03-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20200320_0159'),
        ('formlibrary', '0002_auto_20200215_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beneficiary',
            new_name='Individual',
        ),
    ]
