# Generated by Django 2.2.4 on 2019-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0002_auto_20190513_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='remarks',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
    ]
