# Generated by Django 2.2.10 on 2020-04-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_auto_20200403_0211'),
        ('formlibrary', '0002_auto_20200215_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, max_length=550, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='total_beneficiaries_received_input',
            new_name='total_individuals_received_input',
        ),
        migrations.DeleteModel(
            name='Beneficiary',
        ),
        migrations.AddField(
            model_name='individual',
            name='distribution',
            field=models.ManyToManyField(blank=True, to='formlibrary.Distribution'),
        ),
        migrations.AddField(
            model_name='individual',
            name='program',
            field=models.ManyToManyField(blank=True, to='workflow.Program'),
        ),
        migrations.AddField(
            model_name='individual',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.SiteProfile'),
        ),
        migrations.AddField(
            model_name='individual',
            name='training',
            field=models.ManyToManyField(blank=True, to='formlibrary.TrainingAttendance'),
        ),
    ]
