# Generated by Django 2.2.10 on 2020-04-30 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_merge_20200426_1805'),
        ('formlibrary', '0003_auto_20200427_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='workflow.ActivityUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribution',
            name='modified_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workflow.ActivityUser'),
            preserve_default=False,
        ),
    ]
