# Generated by Django 2.2.10 on 2020-03-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0003_auto_20200320_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ('first_name',)},
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='beneficiary_name',
            new_name='first_name',
        ),
    ]
