# Generated by Django 2.2.10 on 2020-03-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0004_auto_20200331_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='total_beneficiaries_received_input',
            new_name='total_individuals_received_input',
        ),
    ]
