# Generated by Django 2.2.10 on 2020-04-20 00:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0004_case_household'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=550, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('form_verified_by', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=550, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('form_verified_by', models.CharField(max_length=255)),
                ('training_duration', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
