# Generated by Django 2.2.10 on 2020-05-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0002_auto_20200428_0731'),
        ('formlibrary', '0005_auto_20200429_1820'),
    ]

    operations = [
    ]
