# Generated by Django 2.2.10 on 2020-05-04 02:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0006_merge_20200503_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construction',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='construction',
            old_name='form_filled_by',
            new_name='form_completed_by',
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='form_filled_by',
            new_name='form_completed_by',
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='edit_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='form_filled_by',
            new_name='form_completed_by',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='distribution_location',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='initiation',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='input_type_distributed',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='province',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='reporting_period',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='total_individuals_received_input',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='total_received_input',
        ),
        migrations.AddField(
            model_name='construction',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construction',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='item_distributed',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='training',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Modified by'),
        ),
    ]
