# Generated by Django 2.2.10 on 2020-05-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0007_auto_20200519_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='edit_date',
        ),
        migrations.AddField(
            model_name='individual',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Modification date'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Last Modified by'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Modification date'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Last Modified by'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Modification date'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Last Modified by'),
        ),
        migrations.AlterField(
            model_name='training',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Modification date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
