# Generated by Django 2.2.10 on 2020-05-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0007_auto_20200503_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Number of items distributed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distribution',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
    ]
