# Generated by Django 2.2.10 on 2020-06-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0007_auto_20200519_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingAttendance',
        ),
    ]
