# Generated by Django 2.2.10 on 2020-06-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0008_auto_20200521_1610'),
        ('formlibrary', '0008_delete_trainingattendance'),
    ]

    operations = [
    ]
