# Generated by Django 2.2.13 on 2020-09-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0010_auto_20200817_0824'),
        ('formlibrary', '0010_auto_20200826_0922'),
    ]

    operations = [
    ]
