# Generated by Django 2.2.13 on 2020-09-04 12:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import formlibrary.models.case


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_auto_20200428_0711'),
        ('formlibrary', '0011_merge_20200904_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='household',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='household',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='household',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='case',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='case',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.ActivityUser', verbose_name='Last Modified by'),
        ),
        migrations.AddField(
            model_name='case',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Modification date'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=formlibrary.models.case.path_and_rename, validators=[formlibrary.models.case.validate_image]),
        ),
    ]
