# Generated by Django 2.2.10 on 2020-08-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0011_auto_20200803_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='id',
        ),
        migrations.AddField(
            model_name='individual',
            name='case_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='formlibrary.Case'),
            preserve_default=False,
        ),
    ]
