# Generated by Django 2.2.13 on 2020-09-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0012_auto_20200904_0517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ('last_name',)},
        ),
    ]
