# Generated by Django 2.2.10 on 2020-08-10 18:17

import django.core.validators
from django.db import migrations, models
import formlibrary.models.case


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0013_auto_20200805_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='prim_phone',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='primary_number',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='secondary_number',
        ),
        migrations.AddField(
            model_name='household',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Invalid Phone Number. Format: '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='individual',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Invalid Phone Number. Format: '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='individual',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Invalid Phone Number. Format: '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='household',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Invalid Phone Number. Format: '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='individual',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images', validators=[formlibrary.models.case.validate_image]),
        ),
    ]
