# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='program',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='site',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='training',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='initiation',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='office_code',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='program',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='province',
        ),
        migrations.DeleteModel(
            name='DocumentationApp',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='program',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='project_agreement',
        ),
        migrations.DeleteModel(
            name='Beneficiary',
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='TrainingAttendance',
        ),
    ]
