# Generated by Django 2.2.1 on 2019-05-19 07:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Currency Name')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='Currency Symbol')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Currency Code')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='default_language',
            field=models.CharField(default='English-US', max_length=50, verbose_name='Organization language'),
        ),
        migrations.AddField(
            model_name='organization',
            name='form_label',
            field=models.CharField(default='Form', max_length=255, verbose_name='Form Organization label'),
        ),
        migrations.AddField(
            model_name='organization',
            name='indicator_label',
            field=models.CharField(default='Indicator', max_length=255, verbose_name='Indicator Organization label'),
        ),
        migrations.AddField(
            model_name='organization',
            name='site_label',
            field=models.CharField(default='Site', max_length=255, verbose_name='Site Organization label'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stakeholder_label',
            field=models.CharField(default='Stakeholder', max_length=255, verbose_name='Stakeholder Organization label'),
        ),
        migrations.AddField(
            model_name='organization',
            name='theme_color',
            field=models.CharField(default='#25ced1', max_length=50, verbose_name='Organization theme color'),
        ),
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Program Organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='actual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='What was the actual final cost?  This should match any financial documentation you have in the file. It should be completely documented and verifiable by finance and any potential audit', max_digits=20, verbose_name='Actual Cost'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='media/img/', verbose_name='Your Organization Logo'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='actual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='What was the actual final cost?  This should match any financial documentation you have in the file. It should be completely documented and verifiable by finance and any potential audit', max_digits=20, verbose_name='Actual Cost'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='Organization currency', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Currency'),
        ),
    ]
