# Generated by Django 2.2 on 2019-05-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='images/hikaya-activity-logo.png', upload_to='images/'),
        ),
    ]
