# Generated by Django 2.2.1 on 2019-05-22 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190519_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='date_format',
            field=models.CharField(default='DD.MM.YYYY', max_length=100, verbose_name='Organization Date Format'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='theme_color',
            field=models.CharField(default='25ced1', max_length=6, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 6', regex='^.{6}$')], verbose_name='Organization Costum Color'),
        ),
        migrations.AlterField(
            model_name='program',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='edit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='gaitid',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID'),
        ),
    ]
