# Generated by Django 2.2.1 on 2019-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190519_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='date_format',
            field=models.CharField(default='DD.MM.YYYY', max_length=100, verbose_name='Organization Date Format'),
        ),
    ]
