# Generated by Django 2.2 on 2019-05-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190518_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='costum_color',
            new_name='theme_color',
        ),
    ]
