# Generated by Django 2.2 on 2019-05-19 16:51

from django.db import migrations, models
import workflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190519_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='images/hikaya-activity-logo.png', upload_to='images/', validators=[workflow.models.validate_image]),
        ),
    ]
