# Generated by Django 2.2 on 2019-05-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190519_0023'),
        ('workflow', '0002_auto_20190518_0031'),
    ]

    operations = [
    ]
