# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-16 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20161104_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='public_dashboard',
            field=models.BooleanField(default=False, verbose_name='Enable Public Dashboard'),
        ),
    ]
