# Generated by Django 2.2 on 2019-05-25 09:05

from django.db import migrations, models
import workflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20190521_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='images/hikaya-Activity-logo.png', help_text='Image of minimum 2000 width and 500 height, maximum of 100 ko', upload_to='images/', validators=[workflow.models.validate_image]),
        ),
    ]
