# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-29 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20161127_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='level_3_label',
            field=models.CharField(blank=True, default='Component', max_length=255, verbose_name='Project/Program Organization Level 3 label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level_4_label',
            field=models.CharField(blank=True, default='Activity', max_length=255, verbose_name='Project/Program Organization Level 4 label'),
        ),
    ]
