# Generated by Django 2.2.10 on 2020-02-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20200224_0736'),
        ('workflow', '0004_profiletype_organization'),
    ]

    operations = [
    ]
