# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-05 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20161129_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='TolaBookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('bookmark_url', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.TolaUser')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
