# Generated by Django 2.2.1 on 2019-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20190527_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='organization', to='workflow.Organization', verbose_name='Accessible Organizations'),
        ),
    ]
