# Generated by Django 2.2.10 on 2020-02-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_merge_20200225_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholdertype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Organization'),
        ),
    ]
