# Generated by Django 2.2.10 on 2020-02-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_stakeholdertype_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='2 Letter Country Code'),
        ),
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='organization',
            name='zoom',
            field=models.IntegerField(default=5, verbose_name='Zoom'),
        ),
    ]
