# Generated by Django 2.2.1 on 2019-05-28 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20190527_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='gaitid',
        ),
        migrations.AddField(
            model_name='program',
            name='program_uuid',
            field=models.UUIDField(editable=False, null=True, verbose_name='Program UUID'),
        ),
        migrations.AlterField(
            model_name='activityuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, null=True, related_name='organization',
                                         to='workflow.Organization',
                                         verbose_name='Accessible Organizations'),
        ),
    ]
