# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-05 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_tolabookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolabookmarks',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Program'),
        ),
    ]
