# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20161204_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
    ]
