# Generated by Django 2.2.10 on 2020-03-12 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_organization_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=135)),
                ('description', models.TextField(blank=True, max_length=765, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
