# Generated by Django 2.2.1 on 2019-05-28 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20190527_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_uuid',
            field=models.UUIDField(editable=False, default=uuid.uuid4, unique=True, verbose_name='Program UUID'), ),
    ]
