# Generated by Django 2.2.10 on 2020-03-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_organization_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='beneficiary_label',
            field=models.CharField(default='Beneficiary', max_length=255, verbose_name='Beneficiary Organization label'),
        ),
        migrations.AddField(
            model_name='organization',
            name='distribution_label',
            field=models.CharField(default='Distribution', max_length=255, verbose_name='Distribution Organization label'),
        ),
        migrations.AddField(
            model_name='organization',
            name='training_label',
            field=models.CharField(default='Training', max_length=255, verbose_name='Training Organization label'),
        ),
    ]
