# Generated by Django 2.2.10 on 2020-03-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20200306_1040'),
        ('workflow', '0009_projectstatus'),
    ]

    operations = [
    ]
