# Generated by Django 2.2.10 on 2020-03-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_merge_20200315_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'ordering': ('name',), 'verbose_name_plural': 'Project Statuses'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='beneficiary_label',
            field=models.CharField(default='Beneficiaries', max_length=255, verbose_name='Beneficiary Organization label'),
        ),
    ]
