# Generated by Django 2.2.1 on 2019-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20190527_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(default='Default Level 1', max_length=255, verbose_name='Program Name'),
        ),
    ]
