# Generated by Django 2.2.7 on 2020-03-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_merge_20200315_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'ordering': ('name',), 'verbose_name_plural': 'Project Statuses'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='beneficiary_label',
            field=models.CharField(default='Beneficiaries', max_length=255, verbose_name='Beneficiary Organization label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location_description',
            field=models.TextField(blank=True, max_length=765, null=True, verbose_name='Location Description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zoom',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Zoom'),
        ),
    ]
