# Generated by Django 2.2.10 on 2020-03-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_merge_20200315_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'ordering': ('name',), 'verbose_name_plural': 'Project Statuses'},
        ),
        migrations.RemoveField(
            model_name='historicalprojectagreement',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='projectagreement',
            name='approval',
        ),
        migrations.AddField(
            model_name='historicalprojectagreement',
            name='approval_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectStatus', verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='approval_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectStatus', verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='beneficiary_label',
            field=models.CharField(default='Beneficiaries', max_length=255, verbose_name='Beneficiary Organization label'),
        ),
    ]
