# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-06 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20170315_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sects', to='workflow.Sector'),
        ),
    ]
