# Generated by Django 2.2.10 on 2020-03-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20200321_0936'),
        ('workflow', '0011_auto_20200320_0159'),
    ]

    operations = [
    ]
