# Generated by Django 2.2.10 on 2020-03-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20200321_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectagreement',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectStatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectStatus', verbose_name='Status'),
        ),
    ]
