# Generated by Django 2.2 on 2019-06-29 09:56

from django.db import migrations, models
import workflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20190527_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(help_text='Image of minimum 2000 width and 500 height, maximum of 100 ko', null=True, upload_to='images/', validators=[workflow.models.validate_image]),
        ),
    ]
