# Generated by Django 2.2.10 on 2020-03-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20200318_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprojectagreement',
            old_name='approval_status',
            new_name='approval',
        ),
        migrations.RenameField(
            model_name='projectagreement',
            old_name='approval_status',
            new_name='approval',
        ),
    ]
