# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-06 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20170406_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='workflow.Sector'),
        ),
    ]
