# Generated by Django 2.2.10 on 2020-03-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_merge_20200331_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprojectagreement',
            old_name='beneficiary_type',
            new_name='individual_type',
        ),
        migrations.RenameField(
            model_name='projectagreement',
            old_name='beneficiary_type',
            new_name='individual_type',
        ),
        migrations.AlterField(
            model_name='organization',
            name='beneficiary_label',
            field=models.CharField(default='Beneficiaries', max_length=255, verbose_name='Individual Organization label'),
        ),
    ]
