# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-06 17:12
from __future__ import unicode_literals

from django.db import migrations

def moveSectorFKtoM2M(apps, schema_editor):
    Stakeholder = apps.get_model("workflow", "Stakeholder")
    stakeholders = Stakeholder.objects.all()
    for stakeholder in stakeholders:
        if stakeholder.sector:
            sid = stakeholder.sector.id
            stakeholder.sectors.add(sid)
            stakeholder.save()

class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_stakeholder_sectors'),
    ]

    operations = [
        migrations.RunPython(moveSectorFKtoM2M),
    ]
