# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-06 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20170406_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='sector',
        ),
    ]
