# Generated by Django 2.2.10 on 2020-03-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20200329_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='project_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectStatus', verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='project_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectStatus', verbose_name='Project Status'),
        ),
    ]
