# Generated by Django 2.2.10 on 2020-04-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20200329_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectagreement',
            name='beneficiary_type',
        ),
        migrations.RemoveField(
            model_name='historicalprojectagreement',
            name='estimated_num_direct_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='historicalprojectagreement',
            name='estimated_num_indirect_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='historicalprojectcomplete',
            name='beneficiary_type',
        ),
        migrations.RemoveField(
            model_name='historicalprojectcomplete',
            name='direct_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='historicalprojectcomplete',
            name='indirect_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='beneficiary_label',
        ),
        migrations.RemoveField(
            model_name='projectagreement',
            name='beneficiary_type',
        ),
        migrations.RemoveField(
            model_name='projectagreement',
            name='estimated_num_direct_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='projectagreement',
            name='estimated_num_indirect_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='projectcomplete',
            name='beneficiary_type',
        ),
        migrations.RemoveField(
            model_name='projectcomplete',
            name='direct_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='projectcomplete',
            name='indirect_beneficiaries',
        ),
        migrations.AddField(
            model_name='historicalprojectagreement',
            name='estimated_num_direct_individuals',
            field=models.CharField(blank=True, help_text="Please provide achievable estimates as we will use these as our 'Targets'", max_length=255, null=True, verbose_name='Estimated number of direct individuals'),
        ),
        migrations.AddField(
            model_name='historicalprojectagreement',
            name='estimated_num_indirect_individuals',
            field=models.CharField(blank=True, help_text='This is a calculation - multiply direct individuals by average household size', max_length=255, null=True, verbose_name='Estimated Number of indirect individuals'),
        ),
        migrations.AddField(
            model_name='historicalprojectagreement',
            name='individual_type',
            field=models.CharField(blank=True, help_text='i.e. Farmer, Association, Student, Govt, etc.', max_length=255, null=True, verbose_name='Type of direct individuals'),
        ),
        migrations.AddField(
            model_name='historicalprojectcomplete',
            name='direct_individuals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Actual Direct Individuals'),
        ),
        migrations.AddField(
            model_name='historicalprojectcomplete',
            name='indirect_individuals',
            field=models.CharField(blank=True, help_text='This is a calculation - multiply direct individuals by average household size', max_length=255, null=True, verbose_name='Estimated Number of indirect individuals'),
        ),
        migrations.AddField(
            model_name='historicalprojectcomplete',
            name='individual_type',
            field=models.CharField(blank=True, help_text='i.e. Farmer, Association, Student, Govt, etc.', max_length=255, null=True, verbose_name='Type of direct individuals'),
        ),
        migrations.AddField(
            model_name='organization',
            name='individual_label',
            field=models.CharField(default='Individuals', max_length=255, verbose_name='Individual Organization label'),
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='estimated_num_direct_individuals',
            field=models.CharField(blank=True, help_text="Please provide achievable estimates as we will use these as our 'Targets'", max_length=255, null=True, verbose_name='Estimated number of direct individuals'),
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='estimated_num_indirect_individuals',
            field=models.CharField(blank=True, help_text='This is a calculation - multiply direct individuals by average household size', max_length=255, null=True, verbose_name='Estimated Number of indirect individuals'),
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='individual_type',
            field=models.CharField(blank=True, help_text='i.e. Farmer, Association, Student, Govt, etc.', max_length=255, null=True, verbose_name='Type of direct individuals'),
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='direct_individuals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Actual Direct Individuals'),
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='indirect_individuals',
            field=models.CharField(blank=True, help_text='This is a calculation - multiply direct individuals by average household size', max_length=255, null=True, verbose_name='Estimated Number of indirect individuals'),
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='individual_type',
            field=models.CharField(blank=True, help_text='i.e. Farmer, Association, Student, Govt, etc.', max_length=255, null=True, verbose_name='Type of direct individuals'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='project_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectStatus', verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='project_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectStatus', verbose_name='Project Status'),
        ),
    ]
