# Generated by Django 2.2 on 2019-08-10 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_stakeholder_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityuser',
            name='organization',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Organization', verbose_name='Active Organization'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center'),
        ),
    ]
