# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-06 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_remove_stakeholder_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='notes',
            field=models.TextField(blank=True, max_length=765, null=True),
        ),
    ]
