# Generated by Django 2.2 on 2019-08-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_auto_20190810_0346'),
        ('workflow', '0015_auto_20190810_0326'),
    ]

    operations = [
    ]
