# Generated by Django 2.2.10 on 2020-04-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_auto_20200403_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='country_code',
        ),
        migrations.AddField(
            model_name='organization',
            name='country_code',
            field=models.ManyToManyField(blank=True, related_name='organization_country', to='workflow.Country', verbose_name='Country Code'),
        ),
    ]
