# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-14 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_auto_20170623_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='static/img/', verbose_name='Your Organization Logo'),
        ),
    ]
