# Generated by Django 2.2.10 on 2020-04-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_auto_20200403_0138'),
        ('workflow', '0014_auto_20200331_1030'),
    ]

    operations = [
    ]
