# Generated by Django 2.2.3 on 2019-08-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_merge_20190810_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='approval',
            field=models.CharField(blank=True, choices=[('in progress', 'in progress'), ('awaiting approval', 'awaiting approval'), ('approved', 'approved'), ('rejected', 'rejected')], default='New', max_length=255, null=True, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='approval',
            field=models.CharField(blank=True, choices=[('in progress', 'in progress'), ('awaiting approval', 'awaiting approval'), ('approved', 'approved'), ('rejected', 'rejected')], default='New', max_length=255, null=True, verbose_name='Approval Status'),
        ),
    ]
