# Generated by Django 2.2.10 on 2020-04-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_merge_20200403_2020'),
        ('workflow', '0017_merge_20200403_0643'),
    ]

    operations = [
    ]
