# Generated by Django 2.2 on 2019-05-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevelthree',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.District', verbose_name='Admin Level 2'),
        ),
        migrations.AlterField(
            model_name='approvalauthority',
            name='approval_user',
            field=models.ForeignKey(blank=True, help_text='User with Approval Authority', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_approving', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='approvalauthority',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectComplete'),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.SiteProfile'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectAgreement'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Template'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='agreement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser', verbose_name='Request approval'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='estimated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser', verbose_name='Originated By'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='me_reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser', verbose_name='M&E Reviewed by'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='office',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='project_type',
            field=models.ForeignKey(blank=True, db_constraint=False, max_length=255, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectType', verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser', verbose_name='Request review'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='sector',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='project_agreement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='project_type',
            field=models.ForeignKey(blank=True, db_constraint=False, max_length=255, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.ProjectType'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='admin_level_three',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.AdminLevelThree', verbose_name='Administrative Level 3'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='This is the Provincial Line Manager', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.District', verbose_name='Administrative Level 2'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='filled_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='This is the originator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='location_verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='This should be GIS Manager', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='province',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Province', verbose_name='Administrative Level 1'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectComplete'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='approval_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by_agreement', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_agreement', to='workflow.TolaUser', verbose_name='Request approval'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checking', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='estimated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimating', to='workflow.TolaUser', verbose_name='Originated By'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='finance_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reviewing', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='me_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_me', to='workflow.TolaUser', verbose_name='M&E Reviewed by'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='project_type',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectType', verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing', to='workflow.TolaUser', verbose_name='Request review'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='approval_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by_complete', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_agreement_complete', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checking_complete', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='estimated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimating_complete', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Office'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complete', to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='project_type',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectType'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_complete', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Sector'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='admin_level_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.AdminLevelThree', verbose_name='Administrative Level 3'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='This is the Provincial Line Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_approving', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='classify_land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.LandType'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.District', verbose_name='Administrative Level 2'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='filled_by',
            field=models.ForeignKey(blank=True, help_text='This is the originator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_estimate', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='location_verified_by',
            field=models.ForeignKey(blank=True, help_text='This should be GIS Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_gis', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Office'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Province', verbose_name='Administrative Level 1'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProfileType'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stake_approving', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='filled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stake_filled', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='formal_relationship_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_document', to='workflow.Documentation', verbose_name='Formal Written Description of Relationship'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.StakeholderType'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='vetting_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetting_document', to='workflow.Documentation', verbose_name='Vetting/ due diligence statement'),
        ),
        migrations.AlterField(
            model_name='tolabookmarks',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='organization',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='village',
            name='admin_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.AdminLevelThree', verbose_name='Admin Level 3'),
        ),
        migrations.AlterField(
            model_name='village',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.District'),
        ),
    ]
