# Generated by Django 2.2.10 on 2020-04-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_merge_20200403_0643'),
        ('workflow', '0014_auto_20200403_0615'),
    ]

    operations = [
    ]
