# Generated by Django 2.2.4 on 2019-08-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_userinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvite',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'pending'), ('rejected', 'Rejected')], default='pending', max_length=35, verbose_name='Invitation Status'),
        ),
    ]
