# Generated by Django 2.2.10 on 2020-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_merge_20200406_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='admin_boundary',
            field=models.CharField(blank=True, choices=[('ADM0', 'ADM0'), ('ADM1', 'ADM1'), ('ADM2', 'ADM2'), ('ADM3', 'ADM3')], default='ADM0', max_length=10, null=True, verbose_name='Admin Boundary'),
        ),
    ]
