# Generated by Django 2.2.7 on 2020-04-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20200408_0501'),
        ('workflow', '0018_auto_20200407_0146'),
    ]

    operations = [
    ]
