# Generated by Django 2.2 on 2019-08-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20190814_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='activity_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='activity URL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
