# Generated by Django 2.2.10 on 2020-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20200408_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcode',
            name='funding',
            field=models.IntegerField(blank=True, default=10, verbose_name='Funding'),
            preserve_default=False,
        ),
    ]
