# Generated by Django 2.2.4 on 2019-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_auto_20190820_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='name',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Document Name'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='url',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='URL (Link to document or folder)'),
        ),
    ]
