# Generated by Django 2.2.10 on 2020-04-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_auto_20200409_0727'),
        ('workflow', '0020_fundcode_funding'),
    ]

    operations = [
    ]
