# Generated by Django 2.2.7 on 2020-04-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_auto_20200409_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholdertype',
            name='description',
            field=models.TextField(blank=True, max_length=765, null=True, verbose_name='Stakeholder Type Description'),
        ),
    ]
