# Generated by Django 2.2 on 2019-08-30 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_auto_20190829_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomplete',
            name='project_agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_complete', to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
    ]
