# Generated by Django 2.2.4 on 2019-08-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_auto_20190830_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='form_label',
            field=models.CharField(default='Forms', max_length=255, verbose_name='Form Organization label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='indicator_label',
            field=models.CharField(default='Indicators', max_length=255, verbose_name='Indicator Organization label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level_1_label',
            field=models.CharField(blank=True, default='Programs', max_length=255, verbose_name='Project/Program Organization Level 1 label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level_2_label',
            field=models.CharField(blank=True, default='Projects', max_length=255, verbose_name='Project/Program Organization Level 2 label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level_3_label',
            field=models.CharField(blank=True, default='Components', max_length=255, verbose_name='Project/Program Organization Level 3 label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level_4_label',
            field=models.CharField(blank=True, default='Activities', max_length=255, verbose_name='Project/Program Organization Level 4 label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='site_label',
            field=models.CharField(default='Locations', max_length=255, verbose_name='Site Organization label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='stakeholder_label',
            field=models.CharField(default='Stakeholders', max_length=255, verbose_name='Stakeholder Organization label'),
        ),
    ]
