# Generated by Django 2.2.10 on 2020-04-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_auto_20200409_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundcode',
            name='percentage_of_funding',
            field=models.IntegerField(blank=True, null=True, verbose_name='% of Funding'),
        ),
    ]
