# Generated by Django 2.2.10 on 2020-04-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_auto_20200410_1059'),
        ('workflow', '0021_stakeholdertype_description'),
    ]

    operations = [
    ]
