# Generated by Django 2.2.4 on 2019-09-06 06:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('workflow', '0024_auto_20190903_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityUserOrganizationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ActivityUser Organization Group UUUID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('activity_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_user_org_group', to='workflow.ActivityUser')),
                ('groups', models.ManyToManyField(blank=True, related_name='org_groups', to='auth.Group', verbose_name='Organization Groups')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_user_group', to='workflow.Organization')),
            ],
            options={
                'ordering': ('activity_user',),
            },
        ),
    ]
