# Generated by Django 2.2.4 on 2019-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_activityuserorganizationgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='funding_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('in_negotiation', 'In Negotiation'), ('signed', 'Signed'), ('Awarded', 'Awarded'), ('Closed', 'Closed')], default='open', max_length=255, verbose_name='Funding Status'),
        ),
    ]
