# Generated by Django 2.2.10 on 2020-04-27 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_auto_20200414_1653'),
        ('workflow', '0017_merge_20200426_1419'),
    ]

    operations = [
    ]
