# Generated by Django 2.2.10 on 2020-04-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_merge_20200426_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='stakeholder_register',
            field=models.BooleanField(default=False, verbose_name='Has this partner been added to stakeholder register?'),
        ),
    ]
