# Generated by Django 2.2.4 on 2019-09-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('workflow', '0027_stakeholder_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityuserorganizationgroup',
            name='groups',
        ),
        migrations.AddField(
            model_name='activityuserorganizationgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_groups', to='auth.Group', verbose_name='Organization Group'),
        ),
    ]
