# Generated by Django 2.2.13 on 2020-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_auto_20200428_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='household_label',
            field=models.CharField(default='Households', max_length=255, verbose_name='Household label'),
        ),
    ]
