# Generated by Django 2.2.4 on 2019-10-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_auto_20190916_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityuserorganizationgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='User Active'),
        ),
    ]
