# Generated by Django 2.2.4 on 2019-11-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0030_activityuserorganizationgroup_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_stakeholder', to='workflow.Stakeholder'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='contact',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='stakeholder_contacts', to='workflow.Contact'),
        ),
    ]
