# Generated by Django 2.2.7 on 2019-12-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0031_auto_20191105_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcode',
            name='stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholder', to='workflow.Stakeholder'),
        ),
    ]
