# Generated by Django 2.2.7 on 2019-12-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0032_fundcode_stakeholder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitor',
        ),
    ]
