# Generated by Django 2.2.7 on 2019-12-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_delete_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='approval',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('in progress', 'in progress'), ('awaiting approval', 'awaiting approval'), ('approved', 'approved'), ('rejected', 'rejected')], default='new', max_length=255, null=True, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='approval',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('in progress', 'in progress'), ('awaiting approval', 'awaiting approval'), ('approved', 'approved'), ('rejected', 'rejected')], default='new', max_length=255, null=True, verbose_name='Approval Status'),
        ),
    ]
