# Generated by Django 2.2.7 on 2020-01-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_delete_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='email',
            field=models.CharField(default='user@hikaya.io', max_length=100),
        ),
    ]
