# Generated by Django 2.2.7 on 2020-01-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0034_auto_20200109_2051'),
        ('workflow', '0034_auto_20191228_2014'),
    ]

    operations = [
    ]
