# Generated by Django 2.2.7 on 2020-01-23 13:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0035_merge_20200109_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=Decimal('0.00'), max_digits=25, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=Decimal('0.00'), max_digits=25, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=Decimal('0.00'), max_digits=25, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=Decimal('0.00'), max_digits=25, null=True, verbose_name='Longitude'),
        ),
    ]
